# -*- coding: utf-8 -*-
"""Customer Churn Analysis by ANN .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i5NewvNX9asqV_lMEu0SSvL9SsQ6tcX3
"""

from google.colab import drive
drive.mount('/content/drive')

"""# CHURN PREDICTION ANALYSIS BY ANN

import libraries
"""

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

import tensorflow as tf
from tensorflow import keras

tf.__version__

"""Data Gathering"""

df = pd.read_csv("/content/drive/MyDrive/Machine Learning/Churn_Modelling.csv")

df

"""##  DATA PREPROCESSING , DATA CLEANING  DATA QUALITY ISSUE"""

df.head()

df.size

df.shape

df.dtypes

df.describe()

df.info()

df.duplicated().sum()

df.isna().sum()

print(f"Mean of {'Balance'}: {df['Balance'].mean()}")
print(f"median of {'Balance'}: {df['Balance'].median()}")
print(f"Variance of {'Balance'}: {df['Balance'].var()}")
print(f"standard deviation of {'Balance'}: {df['Balance'].std()}")

"""#EDA

## univariate analysis
"""

def univariate_Numerical(df,col):
  print("-"*70)
  print(f"Univariate Analysis of Numerical column : {col}")
  print("-"*70)

  print(f"Mean of {col} : {df[col].mean()}")
  print(f"median of {col} : {df[col].median()}")
  print(f"variance of {col} : {df[col].var()}")
  print(f"standard deviation of {col} : {df[col].std()}")
  print("-"*70)

  plt.subplot(2,2,1)
  sns.kdeplot(df[col], fill = True)
  plt.subplot(2,2,2)
  sns.boxplot(df[col])
  plt.subplot(2,2,3)
  sns.histplot(df[col])
  plt.subplot(2,2,4)
  sns.boxenplot(df[col])
  plt.tight_layout()
  plt.show()

univariate_Numerical(df,'Age')

univariate_Numerical(df,'Tenure')

univariate_Numerical(df,'Balance')

univariate_Numerical(df,'EstimatedSalary')

def univariate_categorical(df, col):
  print("-"*70)
  print(f"Univariate Analysis of Categorical column : {col}")
  print("-"*70)

  print(f"No. of unique Values : \n{df[col].nunique()}")
  print(f"unique Values : \n{df[col].unique()}")
  print(f"Value Counts : \n{df[col].value_counts()}")
  print("-"*70)

  sns.countplot(x = col, data = df, width = 0.5, color = "orange")

univariate_categorical(df,'Geography')

univariate_categorical(df,'Gender')

univariate_categorical(df,'HasCrCard')

univariate_categorical(df, "NumOfProducts")

univariate_categorical(df, "IsActiveMember")

univariate_categorical(df, "Exited")

"""Bivariate Analysis"""

df.columns

def bivariate_numerical(df, col1, col2):
  print(f"Bivariate Analysis of Numerical column : {col1} and {col2}")
  print("-"*70)

  print(f"Correlation between {col1} and {col2} : {df[col1].corr(df[col2])}")
  print("-"*70)

  sns.scatterplot(x = col1, y = col2, data = df, hue= df["Exited"])
  plt.show()

bivariate_numerical(df, "Age", "Tenure")

bivariate_numerical(df, "Balance", "EstimatedSalary")

bivariate_numerical(df, "Balance", "Tenure")

bivariate_numerical(df, "Tenure", "EstimatedSalary")

def bivariate_categorical(df, col):
  print("-"*70)
  print(f"bivariate Analysis of Categorical column : {col}")
  print("-"*70)

  sns.countplot(x = col, data = df, width = 0.5, color = "orange", hue = df["Exited"])

bivariate_categorical(df, "NumOfProducts")

bivariate_categorical(df, "IsActiveMember")

bivariate_categorical(df, "HasCrCard")

bivariate_categorical(df, "Gender")

bivariate_categorical(df, "Tenure")

"""Encoding"""

df.dtypes

df = pd.get_dummies(df, columns = ["Geography"], drop_first = True).drop(["RowNumber", "CustomerId", "Surname"], axis=1)
df

df["Gender"] = df["Gender"].replace({"Male" : 0, "Female":1})

df.head()

df.dtypes

"""Multivariate Analysis"""

df.corr()

plt.figure(figsize = (10,10))
sns.heatmap(df.corr(), annot = True)

plt.figure(figsize = (10,10))
sns.heatmap(df.corr(), annot = True, cmap = "coolwarm")

sns.pairplot(df)

sns.pairplot(df.corr())

df.dtypes

x = df[['CreditScore', 'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts',
       'HasCrCard', 'IsActiveMember', 'EstimatedSalary', 'Geography_Germany', 'Geography_Spain']]

y = df["Exited"]

x.shape

x.columns

x.dtypes

from sklearn.preprocessing import StandardScaler

numerical_columns = ['CreditScore', 'Age', 'Balance', 'EstimatedSalary']

sc = StandardScaler()
sc_array = sc.fit_transform(x[numerical_columns])
x[numerical_columns] = pd.DataFrame(sc_array)

x.head()

x.dtypes

"""train_test_split"""

from sklearn.model_selection import train_test_split

xtrain,xtest,ytrain,ytest = train_test_split(x,y, random_state= 10, test_size=0.2)

xtrain.head()

xtrain.shape

ytrain

xtest.shape

xtest.head()

ytest

"""Model Building by ANN"""

ann = tf.keras.models.Sequential()
ann

#input layer
ann.add(tf.keras.layers.Dense(units = 11, activation = "relu", input_dim=11))

# hidden layer
ann.add(tf.keras.layers.Dense(units = 11, activation = "relu"))
ann.add(tf.keras.layers.Dense(units = 6, activation = "elu"))

# output layer
ann.add(tf.keras.layers.Dense(units = 1, activation = "sigmoid"))

"""Model Compilation"""

ann.compile(optimizer = "adam", loss = "binary_crossentropy", metrics = ["accuracy"])

"""Model Training"""

ann.fit(xtrain,ytrain, batch_size=32, epochs =100)

ann.summary()

ann.get_weights()

"""Evaluation"""

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

ytrain_pred = ann.predict(xtrain)

ytrain_pred

ytrain_pred_list = []
for i in ytrain_pred:
  if i > 0.5:
    ytrain_pred_list.append(1)
  else:
    ytrain_pred_list.append(0)

accuracy_score(ytrain, ytrain_pred_list)

confusion_matrix(ytrain, ytrain_pred_list)

print(classification_report(ytrain, ytrain_pred_list))

"""Prediction"""

xtest.head(5)

ytest

ann.predict(xtest.head(5))

for i in ann.predict(xtest.head(5)):
  if i > 0.5:
    print("Exited")
  else:
    print("Not Exited")

xtrain.columns

xtrain.head(1)

def myfunction(CreditScore, Gender, Age, Tenure, Balance, NumOfProducts,
       HasCrCard, IsActiveMember, EstimatedSalary, Geography_Spain, Geography_Germany):


  input_data = pd.DataFrame([[CreditScore, Gender, Age, Tenure, Balance, NumOfProducts,
       HasCrCard, IsActiveMember, EstimatedSalary, Geography_Spain, Geography_Germany]], columns = ['CreditScore', 'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts',
       'HasCrCard', 'IsActiveMember', 'EstimatedSalary', 'Geography_Spain', 'Geography_Germany'])

  numerical_columns = input_data[['CreditScore', 'Age', 'Balance', 'EstimatedSalary']]

  sc = StandardScaler()
  sc_array = sc.fit_transform(numerical_columns)

  input_data[numerical_columns.columns] = pd.DataFrame(sc_array)

  input_data['Gender'] = input_data['Gender'].replace({'Male' : 0, 'Female' : 1})

  print(input_data)


  ann.predict(input_data)

  if ann.predict(input_data) > 0.5:
    print("Customer Exited")
  else:
    print("Customer Not Exited" )

"""CreditScore, Gender, Age, Tenure, Balance, NumOfProducts, HasCrCard, IsActiveMember, EstimatedSalary, Geography"""

df.head(1)

myfunction(619,	"Male"	,42,	2	,1,	1,	1,	1,	101348.88,1,0)

